### ISSUE TITLE
Content added

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/regex-match-scan-grep-methods-readme#1]
@AnnJohn @StevenNunez @jmburges, take a look...

**Comment by AnnJohn** [comment]
Assigned to @StevenNunez for review

**Comment by octosteve** [comment]
@dfenjves Made a note here https://github.com/learn-co-curriculum/regex-match-scan-grep-methods-readme/commit/924f1c5e80946f7fe16e4c278fccc8894640730e#commitcomment-14099803 This is good to merge otherwise.
