### ISSUE TITLE
Spec missing info

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/regex-match-scan-grep-methods-readme#2]
Just a typo, but the spec is missing the "?" it states expect(valid_phone_number(number)).to be(false) instead of expect(valid_phone_number?(number)).to be(false)

**Comment by AnnJohn** [comment]
i think this issue was for another lesson- since there are no spec files here. but fixed it in that [lesson](https://github.com/learn-co-curriculum/regex-lab)
