### ISSUE TITLE
Useful additional resources

### ISSUE THREAD

**Issue by Rygel-XVI** [learn-co-curriculum/regex-match-scan-grep-methods-readme#7]
For the Regex section I found that though it explained sort of how it works and a few ways to play around with it I found I had a ton of questions about why it works the way it does (especially the ruby functions). I found the website https://www.regular-expressions.info/   far more helpful as it delved a lot more into how the system works which clarified things a lot.

**Comment by curiositypaths** [comment]
Hi There,

Thank you for the suggestion. We will review the resource.

As always, thank you for contributing 💙
